### ISSUE TITLE
Ansible mixin

### ISSUE THREAD

**Issue by decentral1se** [getporter/porter#1060]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an Ansible mixin. If I get time, I'll try it myself.

Just creating this issue to track that more transparently if others are interested.

**Describe the solution you'd like**
We have an Ansible porter mixin.

**Describe alternatives you've considered**
Using the exec mixin :point_right: https://git.autonomic.zone/decentral1se/gitea-cnab

**Additional context**
Guess https://github.com/deislabs/porter-skeletor is the place to start

**Comment by LvffY** [comment]
Hello

I'm starting to using porter with my company and we have a LOT of ansible playbook that we'd like to orchestrate through Porter. For now we're using the **exec** mixin, but a built-in mixin (like for **Terraform** would be very nice. 

@carolynvs is there any plan to support this ? 

Best regards

**Comment by carolynvs** [comment]
I'm not aware of anyone who has made an ansible mixin. If you are interested in creating one yourself, we have a template to get you started and guidance on how to distribute and publicize a mixin: https://porter.sh/mixin-dev-guide/.

**Comment by carolynvs** [comment]
We have a couple different official channels: https://porter.sh/community. I recommend asking general questions about how to make a mixin on our [discussion board](https://porter.sh/forums/) since its searchable and therefore if someone else is trying to make a mixin, could learn from whatever you ask about. But I'm happy to answer questions wherever.

**Comment by LvffY** [comment]
For anyone interested, a  [discussion is opened about complex architecture](https://github.com/getporter/porter/discussions/1934)

**Comment by LvffY** [comment]
@carolynvs I think I have a [first working setup](https://github.com/LvffY/ansible-mixin). Could you tell me what are the next steps to get this plugin added in this repo (Code/docs review, how to release, etc.) ?

**Comment by carolynvs** [comment]
That's great! I'm glad you got it working. Here are some next steps for sharing your mixin with the community:

1. Add instructions and examples for using your mixin to your readme so that people know what the yaml should look like.
2. Publish a release of your mixins to your github releases page in your repository. The `mage publish` target can help with that which it looks like you already have hooked up to your azure pipeline.
3. Test that you can install your mixin with `porter mixins install --url https://github.com/LvffY/ansible-mixin/releases/download --version REPLACE_ME`
4. Submit a pull request to our packages repository to add your mixin to the list of available mixins. https://github.com/getporter/packages/blob/main/mixins/index.json
5. After that pull request is merged, people can find your mixin by running `porter mixins search ansible`

**Comment by LvffY** [comment]
@carolynvs Seems good to me.

See https://github.com/getporter/packages/pull/22
