### ISSUE TITLE
Unable to edit parameters on Windows

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#1241]
## Describe the bug
It is possible to generate a parameter set using `porter parameters generate` but when trying to edit it afterwards with `porter parameters edit` it fails

## To Reproduce
1. Run `porter parameters generate myparams`
2. Use any porter.yaml that defines one or more parameters
3. Run this porter command `porter parameters edit myparams`
```
/C: /C: Is a directory
Error: unable to open editor to edit parameter set: exit status 126
```

## Expected behavior
An interactive editor that allows for updating and/or adding missing parameters in the existing parameter set

## Porter Command and Output
```
$ porter parameters edit myparams
/C: /C: Is a directory
Error: unable to open editor to edit parameter set: exit status 126
```
The "C:" part probably relates to the fact that I'm running under Windows, where porter gets installed in "C:\Users\<initials>\.porter\porter"

## Version
Copy the output of `porter version` below

porter v0.28.1 (dd9056f3)

**Comment by carolynvs** [comment]
I wasn't able to reproduce this on Windows using Powershell or WSL2 with `v0.29.1` but we haven't made any recent changes that would have fixed it. 

Are you still able to reproduce this error? If so, which shell are you using and are on Windows or are you in WSL? 

What is the value of your `EDITOR` and `SHELL` environment variables? If you have EDITOR set, can you try unsetting it then re-running the command again? I'm wondering if perhaps your editor and shell are misaligned, so that Porter is trying to open a windows formatted path in bash, or vice versa.

**Comment by jasmdk** [comment]
I can not reproduce it and we implemented another solution to not manage parametersets directly, especially because we have a set of bundles that shares some of the same configuration values.
You may close this for all I care.

**Comment by carolynvs** [comment]
I'm glad to hear that you have a workaround!
