### ISSUE TITLE
Publish example bundles to ghcr.io?

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1280]
It looks like [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/) may now support CNAB/Porter bundles!  Do we want to start publishing Porter's main example (and CI?) bundles to its inherited `ghcr.io/getporter` registry?

If so, 

- [x] Test out the ghcr registry and validate it's all good (oh, perhaps update https://porter.sh/compatible-registries/ while we're at it)
- [ ] Update bundle publishing CI to push to ghcr.  May want to update the actual porter.yaml manifests as well?

**Comment by carolynvs** [comment]
I think we are really close but not there yet. Based on what I've heard on the chatter in our Slack channel, push works but not pull yet due to the media type *mumble mumble*. 😀 But yes I would love to use GitHub Container Registry once it's ready for bundles!

**Comment by MChorfa** [comment]
I tested yesterday and it was conclusive for me :) https://github.com/orgs/mch0rfa/packages

**Comment by carolynvs** [comment]
Oh cool! I didn't follow that thread on slack far enough to see that they patched pull. 💯

**Comment by squillace** [comment]
Here is the deal: you must not have the repository _private_; if you do, you must manually set the registry/packages to be public or it will not work to pull! This makes complete sense, so it does work like this:

- if the repo is public, push and pull both work. You MUST however currently use a personal access token to auth for push. The fix for this is in the works so eventually you'll be able to use `github.token` but not now.
- if the repo is NOT public, push with a personal token works and pull with a docker login using the personal token works, but NOT public pulling the bundle until you manually make the packages for that repo public (something you cannot reverse, per the docs).

Assuming that we're talking about public repos -- and i think we are -- it all works!!!! @carolynvs

**Comment by carolynvs** [comment]
Thanks for digging in and figuring out the details. I spoke with the other maintainers and we'd like to do dual pushing for a while between docker hub and GitHub Container Registry, maintaining our bundles and examples on both for a period of time until it is stable to just be on one.

**Comment by squillace** [comment]
I was doing that -- you can do it, but there's something wonky with the azure/docker-login action and I found I could do it fine with the docker/login action.

**Comment by squillace** [comment]
I agree. Time to move.
