### ISSUE TITLE
Publish: Update/support tag and repository flags

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1335]
Implementation of the corresponding section of https://github.com/getporter/porter/issues/1151:

Today, Porter's publish command offers the `-t/--tag` flag to override the bundle reference (and update the invocation image name accordingly) prior to pushing to an OCI registry.  The flag naming was directly inspired by the correlate from the `docker build` command, but we've since realized that we'd like to restrict it to just representing a Docker tag override, rather than an override for the bundle reference.  Therefore, we propose to redefine this flag's purpose and add a new flag, `--reference`, to serve the purpose of this flag's previous responsibility.

* `-t/--tag`: override the Docker tag of the bundle reference (and invocation image), e.g. `latest`, `v0.1.1`, etc.
* `--reference`: override the bundle reference entirely (and rename the invocation image accordingly), e.g. `otherregistry.com/otherorg/mybuns:v0.1.0`
* `--registry`: override the bundle registry

## AC

- the `tag` flag is updated to represent the Docker tag portion of the bundle for `porter publish`
- the `reference` flag is added for `porter publish`
- the `registry` flag is added

**Comment by carolynvs** [comment]
I just realized that the proposal is to have `--repository` be the entire destination, e.g. `docker.io/myorg/mybundle:v1`. That will be confusing, just like tag is today, because repository refers to this part only `docker.io/myorg/mybundle`. Here's the Docker [documentation](https://docs.docker.com/docker-hub/repos) to help show the relationship: one repository has many tags.

> A single Docker Hub repository can hold many Docker images (stored as tags).

Since we are trying to match the terms better, let's not redefine repository. I have been searching all over for an accepted term for the entire reference and haven't found one. Hah, pretty sure this is why we used tag to begin with (besides following the convention set by the docker cli).

Breaking down the parts of a reference we have `REGISTRYHOST/ORG/BUNDLE_NAME:TAG` where:

* Really the term registry refers to just `docker.io` or `quay.io`. However since swapping just the host of the registry is usually not what people do, they also change the org and other subpaths as well, we are calling this entire part `REGISTRYHOST/ORG` the registry. So someone can change where they are publishing a bundle using `--registry quay.io/differentuser/subproject` **Do you think this is confusing or helpful?**

* The repository is composed of `REGISTRYHOST/ORG/BUNDLE_NAME`

* The tag refers to the final component of the reference `TAG` e.g. `latest` or `v1`

Some examples using the new flags

```
$ porter publish --tag v1

$ porter publish --repository quay.io/carolynvs

$ porter publish --name moarbuns

$ porter publish --reference quay.io/carolynvs/moarbuns:v1
```

I just found that in the CNAB Claims spec we have `bundleReference` which is 

> A canonical reference to the bundle

So that seems like a good name for it. Also the docker library uses the term reference as well.

**Comment by vdice** [comment]
I'm on board with the direction stated above.  Thank you for the thorough research and consideration around these terms!

One question.  Looking at this line:

> $ porter publish --repository quay.io/carolynvs

Should it be `porter publish --registry quay.io/carolynvs` in line with how registry is used/proposed in https://github.com/getporter/porter/issues/1333 and https://github.com/getporter/porter/issues/1334?

I will update instances of `repository` mentioned in those tickets to be `reference` as mentioned above.

**Comment by carolynvs** [comment]
Oops! Yes, thanks it should be registry. Let me fix that.
