### ISSUE TITLE
Support referencing images by tag and embedded the digest in the bundle

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1357]
I was looking into how images.NAME.tag is used and it doesn't match how I thought it worked at one point. I thought we had implemented looking up the digest at build when only tag is specified but we aren't doing that. Maybe we never did? 

The tag field isn't documented well on how it is used and isn't terribly useful right now. It basically gives people a place to say what tag they think they are using. The way it is implemented now, we should be setting digest as a required field and validating that it is set, because otherwise we generate an invalid bundle.json with an empty contentDigest.

Let's rethink what we _want_ to do with tag and what would be useful for desired scenarios: airgap and inspectability (seeing what is used by the bundle).

**Comment by carolynvs** [comment]
We discussed and want to implement what in my heart I always thought porter did. Let's pull the image at build, and embed the digest in the image reference.

**Comment by carolynvs** [comment]
While I was documenting the porter manifest I noticed that we have fields on image that should not be set by the user, and either porter should fill in for you on the bundle.json, or should just omit them entirely.

* imageType - I don't get why anyone would set this. Can we default to docker or oci-image? Is there a difference?
* Size - why would anyone set this manually? we can set it if it's important to be set on the bundle.json
* mediaType (e.g. application/vnd.docker.distribution.manifest.v2+json) - can't we set this?
* labels: is this intended to be set by the user? Or should this value be populated based on the image?
* contentDigest - let's check that this is being set in bundle.json correctly. It's not the repo digest, and is a digest of the contents of the image. It's not exposed in the manifest and shouldn't be.

**Comment by jasmdk** [comment]
Related to this, we have learned to ALWAYS specify the digest because if we only specify the tag and it points to a multi-architecture build, then images for all architectures are included in porter - not only amd64 which we are interested in.
Furthermore some repos tend to rebuild their images so that digest changes over time. This prevents us from doing "porter achive" when the bundle was referencing an image using a digest that no longer exists in the source registry!
As an example, we have a bundle referencing image `quay.io/keycloak/keycloak:18.0.0` which had digest `sha256:795ee60a250374ef38c0ef0b68c1ccd999efa3744e71a66876ac6794046a9669` at the time of publishing our bundle, but now the digest is `sha256:abaf9c02ada7f0ff01f5742c2004ade0f9a5a5997d25fd443a3c0cf8ffe1847a` and the old one no longer exist and "porter achive" fails with:
`Error: error preparing artifacts: GET https://quay.io/v2/keycloak/keycloak/manifests/sha256:795ee60a250374ef38c0ef0b68c1ccd999efa3744e71a66876ac6794046a9669: MANIFEST_UNKNOWN: manifest unknown; map[]`

**Comment by carolynvs** [comment]
I think the second problem (the published bundle references an image digest that doesn't exist anymore) may be a bug. When running archive, we should be pulling the images directly from the published bundle, and not trying to download the original source.

Thanks for letting me know about that!

**Comment by carolynvs** [comment]
I've created https://github.com/getporter/porter/issues/2050 to verify and track the bug.

**Comment by carolynvs** [comment]
During porter build, we should check if any image has a tag (but no digest defined) pull the image, and update the bundle.json/porter.yaml with the resolved digest. That way when someone uses the bundle, it will use the digest resolved at build time and not the tag at runtime.

```yaml
images:
  mysvc:
     repository: docker.io/carolynvs/mysvc
     # digest: sha256:abc123, user can specify the tag and porter build will resolve and lock in the digest.
     tag: 1.1.1
```
