### ISSUE TITLE
Windows E2E failure

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1389]
Seeing the following CI failure around the Windows E2E tests: https://dev.azure.com/getporter/525ee0af-eff4-4f16-9127-da829779137b/_apis/build/builds/593/logs/70

It seems to time out on invoking `exec.exe --version ...`

Not sure if this is CI/Win agent related or a bug in our Windows binary build(s) -- or other!  But it seems to be cropping up lately in CI and thus failing builds for unrelated PRs, etc.

**Comment by carolynvs** [comment]
There were three problems that caused this:

1. Docker Desktop doesn't start the docker service when it detects that an update is available. I have updated our windows agent image to disable checking for updates. We will just need to refresh periodically. ✅
2. My logic in our magefile that waits for docker service to come up, and it using debug logging instead of info logs so we didn't see that we were waiting on docker to start.
3. That same logic is waiting waay too long. I meant for it to wait a minute, not an hour! 😂

**Comment by carolynvs** [comment]
This is fixed, builds are passing again.
