### ISSUE TITLE
Documentation: Contributing tutorial 

### ISSUE THREAD

**Issue by iennae** [getporter/porter#1400]
## Improvements to Contributing tutorial requested 

* Slight update to "what successful Mage install looks like" 
```
Targets:
  configureAgent       sets up an Azure DevOps agent with Mage and ensures that GOPATH/bin is in PATH.
  ensureMage           Ensure Mage is installed and on the PATH.
  getMixins            Install mixins used by tests and example bundles, if not already installed
  setBinExecutable     Run `chmod +x -R bin`.
  startDocker          Ensure the docker daemon is started and ready to accept connections.
  testE2E              Run end-to-end (e2e) tests
  useXBuildBinaries    Copy the cross-compiled binaries from xbuild into bin.
 ```
  
  current output of mage has changed slightly. 
  
 * The tutorial starts out with installing mage but then doesn't appear to use it throughout (appears to be necessary for running make). Helpful to explain that a little bit. 
  
* Missing link for Mage https://magefile.org/ 
  
* Assumes bash shell. Update to be clear about that.  (Default shell on macos is zsh now) 

* In create a new bundle, not specifying the path of porter so if otherwise installed won't be using what was just built. 
* Error received in running install
```➜  hello-world /tmp/porter/bin/porter install
WARNING: the tag field has been deprecated; please replace with a value for the registry field on the Porter manifest instead
===> See https://porter.sh/author-bundles/#bundle-metadata for more details
installing HELLO...
/cnab/app/run: line 2: /cnab/app/porter-runtime: No such file or directory
Error: 1 error occurred:
	* container exit code: 127, message: <nil>

```
* In change porter, be clear the change in creation of file.
* Update "Run ./bin/porter --name YOURNAME to try out your new command." to "./bin/porter hello --name YOURNAME"
* Next steps: link to contributing guidelines https://github.com/getporter/porter/blob/main/CONTRIBUTING.md at the bottom.

**Comment by joshuabezaleel** [comment]
Hi @iennae , I was just going through the contributing tutorial docs to set up mine. I thought that it would be a bit confusing for first-time contributors because the `mage` command and its expected output written on the docs (e.g. targets getMixins, testE2E, etc.) is expected to be run inside the `porter` directory after it is cloned to the contributor's machine but the instruction to clone the repo is after the mage section. What do you think?

**Comment by joshuabezaleel** [comment]
Not directly related to "contributing tutorial" but I think still related to it since going to the "quickstart" page is recommended on the contributing tutorial page. 
I got these lint errors when I try to build the bundle according to the `porter.yaml` file on the [`quickstart`](https://porter.sh/quickstart/#create-a-new-bundle) page and I think it should also be wrapped in quotes according to [this guide](https://porter.sh/best-practices/exec-mixin/#quoting-escaping-bash-and-yaml) of exec mixins. 

![image](https://user-images.githubusercontent.com/7043511/104815544-c2db3400-5847-11eb-8d05-d98b09c0d24b.png)

**Comment by carolynvs** [comment]
Thanks for trying it out and giving feedback on what needs to be improved! I'll try to address some of these items today.

**Comment by carolynvs** [comment]
@iennae I'm not sure what this means?

> In change porter, be clear the change in creation of file.

---

I don't get an error when running porter install and I'm not sure what would cause that. :thinking: Can you try running `make build` and then building the bundle again?

---

> In create a new bundle, not specifying the path of porter so if otherwise installed won't be using what was just built.

The paragraphs just above where I have them run porter commands I have them alias porter to their local build. You must set PORTER_HOME and it's just easier to make the alias while testing IMO.
