### ISSUE TITLE
Quickstart: `porter install` fails

### ISSUE THREAD

**Issue by JasonFreeberg** [getporter/porter#1486]
## Describe the bug
I installed Porter on my Windows machine and started the quickstart to learn more. I got to the installation step, and I got the following error:

```
PS C:\Users\jafreebe\Desktop\porter-demo> porter install
installing porter-hello...
Unable to find image 'getporter/porter-hello-installer:v0.1.0' locally
v0.1.0: Pulling from getporter/porter-hello-installer
0400ac8f7460: Pulling fs layer
<truncated docker pull logs>
f2944a51eeb1: Pull complete
Digest: sha256:14f6045ad49a4f8dc84ce26d2d41d2e6762ab5b56ffe6396e06b275ce37c9a8c
Status: Downloaded newer image for getporter/porter-hello-installer:v0.1.0
WARNING: the tag field has been deprecated; please replace with a value for the registry field on the Porter manifest instead
===> See https://porter.sh/author-bundles/#bundle-metadata for more details
executing install action from porter-hello (installation: porter-hello)
Error: unable to resolve step: unable to build step template data: unsupported required extension: sh.porter.file-parameters
Error: 1 error occurred:
        * container exit code: 1, message: <nil>
```

## To Reproduce
1. Follow the Porter quickstart on a Windows machine

## Expected behavior
Porter installation completes 

## Version

porter v0.34.4 (ccebf071)

**Comment by carolynvs** [comment]
Oops, that's no good. I have seen that error before when an old version of porter tries to use a new bundle. Let me investigate and see what went wrong on our side.

Thanks for letting us know about the problem!

**Comment by carolynvs** [comment]
Here's what I have found after trying out a few combinations:

porter v0.34.4 with getporter/porter-hello:v0.1.0 works ✅
porter v0.34.4 with getporter/porter-hello:v0.1.1 works ✅
porter v0.31.2 (and lower) with getporter/porter-hello:v0.1.0 works ✅
porter v0.31.2 (and lower) with getporter/porter-hello:v0.1.1 fails with the same error that you got ❌

So I'm wondering if you really are using an older version of porter? You can download the latest at this URL https://cdn.porter.sh/v0.34.4/porter-windows-amd64.exe. Maybe try redownloading and instead of running `porter install` use `.\path\to\porter-windows-amd64.exe install`?

**Comment by carolynvs** [comment]
Closing since we haven't heard back in a while but if you are still seeing problems, let us know and I'll reopen.
