### ISSUE TITLE
Porter publish does not reach into a specific file

### ISSUE THREAD

**Issue by jeffersonbenson** [getporter/porter#1498]
## Describe the bug

In a repository I'm working with, if I am in the root of the directory and the porter.yaml file exists in a porter folder, I am unable to run `porter publish --file porter/porter.yaml` in order to publish the bundle. Additionally specifying an absolute path to the porter.yaml file seems to produce the same issue. 

It would appear that porter is failing to take into account a folder named porter, and removes it from the path

## To Reproduce
1. Place porter.yaml file in a folder called porter
2. From the higher folder run `porter publish --file porter/porter.yaml`
3. See error

## Expected behavior

Porter should be able to publish the bundle with the specified file

## Porter Command and Output
```
$ porter publish --file porter/porter.yaml
Building bundle ===>
Error: unable to generate manifest: could not read the manifest at "porter.yaml": open /<redacted>/porter.yaml: no such file or directory

```

## Version
Copy the output of `porter version` below

[e.g. porter v0.14.1-beta.2 (72dd5df)]

porter v0.34.4 (ccebf071)

**Comment by carolynvs** [comment]
Gotcha, thanks for the issue. This is both a known problem with porter (always using the current directory for the build context) and looks like a newly introduced bug around locating the porter.yaml.

I think we need to introduce a second flag, similar to how `docker build -f /path/to/Dockerfile /path/to/build/context` works so that we aren't tied to the current directory. Then have the paths in the porter.yaml be in relation to the build context directory.

Let me know if that aligns with what you were hoping Porter would do, or if I'm misunderstanding the use case!

**Comment by jeffersonbenson** [comment]
So for us the build context can totally be in the same directory as the porter.yaml, and probably should imho. 

For a larger context we're using a CI/CD pipeline to build and test bundles on PR from our devs, so right now the quick and dirty solution is just to have our build script cd into the directory with the porter bits and go from there, but it was a bit confusing to see the option for `--file` without the expected functionality.

**Comment by carolynvs** [comment]
Agreed! That flag doesn't work the way it should. Thanks for the feedback on how you plan on using the flag.

A workaround until we fix the bug with --file is to ensure that the porter.yaml is in in the current directory where you run porter build. Depending on people's setup that may involve copying the porter.yaml some other place than where it is stored in the repo. 

1. named porter.yaml
2. run porter build without the --file flag from the same directory as porter.yaml

This really should be fixed, I just can't guarantee how soon, which is why I'm making sure people understand how it's broken and the workaround.

**Comment by carolynvs** [comment]
@vdice I remember that we ended up hard coding some of the lookups for the user-defined porter.yaml to "porter.yaml" and don't take into account opts.File. Do you remember why we had to hard-code it? I recall you found problems related to the generated .cnab/porter.yaml but I'm unclear on if I switch to always use opts.File if I should be on the lookout for unintended problems?

**Comment by vdice** [comment]
> @vdice I remember that we ended up hard coding some of the lookups for the user-defined porter.yaml to "porter.yaml" and don't take into account opts.File. Do you remember why we had to hard-code it?

Let me revisit this area in the code to refresh my memory here and reply...

**Comment by carolynvs** [comment]
Don't you remember laughing with me and saying "No one will ever need _this_!" and then evilly hardcoding the value? 😂

**Comment by vdice** [comment]
Ah yes, it was because further plumbing would be needed to update applicable, hard-coded file path values (user-supplied manifest, Porter's internal version, the bundle.json file).  We currently have a lot of spots where it assumes we're always in the bundle directory itself.  Oh, and Porter's build logic doesn't have an option to ingest a `File` value... it's all tied to that same assumption.  Hence, the disconnect and broken-ness.

I'm currently seeing what it would look like to update these areas to hinge off a different location (namely, the directory that holds the user-supplied File value)...

**Comment by carolynvs** [comment]
I am leaning towards being flexible about the filepath and directory, similar to how docker build allows you to set both a context directory and dockerfile path. I have had people in the past say that they want to ship files from the root of their repo but not keep the porter.yaml at the root.
