### ISSUE TITLE
Why aren't the `name` or `registry` properties overrideable by flag?

### ISSUE THREAD

**Issue by philliphoff** [getporter/porter#1503]
While I see that the `version` property of the `porter.yaml` can be overridden on the command line during build, why not also the `name` or `registry` properties?  If, for example, two developers each clone their team's repo (which uses Porter for deployment) and each want to test their local changes in their own test environment, must they modify (at least) the `registry` property in order to redirect their build to their individual registries?  Is there a better way of managing that iterative testing of applications via Porter bundles?

**Comment by vdice** [comment]
Hi @philliphoff, great questions.  Porter does allow overriding both values, but in different commands.  On [build](https://porter.sh/cli/porter_bundles_build/), `name` and `version` can be overridden.  We decided to place registry-related overrides in Porter's [publish](https://porter.sh/cli/porter_publish/) command.  There, `registry`, `tag` and `reference` may all be overridden on publish.

That being said, I can see how it might be desired that all of `name`, `version` _and_ `registry` might be "set" at build time so that no additional flags are needed on `porter publish`.  However, @carolynvs and I have chatted about removing the registry-related fields from the manifest itself.  We're not sure that having them included in the manifest was a wise choice -- especially as we see more and more use cases of wanting the same bundle to be "tagged" and/or hosted in a variety of differing registries.

While the discussion above progresses, would building with `name` and/or `version` overrides and then publishing with a `registry` override work in the interim?  @carolynvs wrote up a nice blog post around scenarios here that may be helpful: https://porter.sh/blog/ci-flags/

**Comment by squillace** [comment]
BUT let's point out a few things: if you standardize on dynamically naming bundles, you sacrifice any GitOps, pull-style approach because there's no record of your work without locating and keeping the logs of the GH action run. 

Make sure that IF you decide on moving to fully dynamic, you do NOT have any intention of formally associating those values with any specific git commit. It's fine if you do it! But make it a formal decision.

**Comment by carolynvs** [comment]
I just want to add that I would personally like to include more of the data that Porter has available to it in the templating. While some tasks are easier to do with other solutions, like porter publish --registry vs {{ bundle.registry }}, I don't want to let our preconceived notions of what tasks people are undertaking to cause us to avoid adding in certain values and therefore block tasks we didn't anticipate.

I'm going to take a pass at making more templating fields available (since selfishly I need them right now), with the caveat that that in future versions they may not continue to be available. For example if we remove registry from porter.yaml, {{ bundle.registry }} would stop working, though in that particular case having access to the registry used _at runtime_ could be a useful substitute. So for example:

porter install --reference my-alt-registry/some-bundle:v1.0.0

could make the following templated values available

* installation.registry
* installation.version

I'm keen on having access to the ambient environment variables during bundle execution. So something like `env.stuff` would provide the value of the environment variable $STUFF.

**Comment by carolynvs** [comment]
I just re-read the OP and realized that you meant "why aren't they exposed via a CLI flag" when I thought you mean "in our set of template variables". 🤦‍♀️  Happy Monday!

**Comment by philliphoff** [comment]
Yes, I *think* I can do what I want w.r.t. name/version/registry via the CLI build/publish/install arguments that override `porter.yaml`.  (Currently we are overwriting those values in `porter.yaml` with generated values as one of our CI steps.) Hopefully using the CLI arguments is a better way to do it. :-)

**Comment by carolynvs** [comment]
I'm closing this because it seems that the question has been answered. Just let me know if we should revisit it!
