### ISSUE TITLE
Is CNAB Spec verification workflow on the roadmap?

### ISSUE THREAD

**Issue by seb-bah** [getporter/porter#1519]
**What is your question?**
Is the CNAB Verification workflow in Porter's Roadmap for implementation anytime soon? [CNAB Verification Workflows](https://github.com/cnabio/cnab-spec/blob/main/303-verification-workflows.md)

"In order to download and verify a bundle, a compliant runtime MUST take the following steps..." 

I'm assuming that this would involve implementing including a tool such as Signy into Porter?

**Comment by carolynvs** [comment]
Good question! The CNAB Security spec hasn't been finalized yet. Once it's implemented in signy fully (see https://github.com/cnabio/signy/pull/80) we want to update signy's implementation a bit so that we can use it as a library to support the Security spec. I would love to see that happen in 2021.

I've updated the [roadmap](https://porter.sh/roadmap) to show that it's planned but isn't ready to start work yet.

**Comment by carolynvs** [comment]
Closing. This is on this year's roadmap.
