### ISSUE TITLE
Inconsistent Image Size across all the Plugins Page

### ISSUE THREAD

**Issue by DARK-art108** [getporter/porter#1627]
## Describe the bug
The plugin pages like Kubernetes, azure, and Hashicorp have inconsistent image sizes which look bad, resizing it and making it in a similar dimension would be great!

## To Reproduce
1. Take a look at Plugin Pages: Kubernetes.md, azure.md, hashicorp.md

## Expected behavior
_Resizing Images_ to similar sizes which makes page UI perfect would be nice.

**Comment by carolynvs** [comment]
I just checked the pages and they do all have the same width (300px). However since one of the logos isn't square, they all look different. If we swapped out the azure logo for a this one, I think they would look more consistent.
![Azure-A-256px](https://user-images.githubusercontent.com/1368985/121564950-9801a000-c9e1-11eb-9a35-2c86772022d9.png)

**Comment by DARK-art108** [comment]
Yes @carolynvs we can change the azure logo to look similar to others!

**Comment by carolynvs** [comment]
Thanks!
