### ISSUE TITLE
Adding More Badges to Readme.md

### ISSUE THREAD

**Issue by DARK-art108** [getporter/porter#1635]
**What design is being proposed?**
We can have some badges like _docker pulls_ , _Twitter followers_, _go report_ and others mentioned below in Readme.md!
![badges](https://user-images.githubusercontent.com/53623244/121915582-f7004580-cd50-11eb-9344-b3a26d676489.PNG)

**Additional Context**

**Risks/Concerns**

**What other approaches were considered?**

**Implementation details**

# Checklist
- [ ] An announcement of this proposal has been sent to the Porter mailing list: https://porter.sh/mailing-list
- [ ] This proposal has remained open for at least one week, to allow time for community feedback.

**Comment by carolynvs** [comment]
Let's consider which badges would be helpful to someone to see on our readme. I don't want to show a badge just because we can, let's make sure that each badge communicates information that is necessary to our users.

* docker pulls - I'm not sure that showing people this number right now would help them make a decision. Our images are mainly used by us at this point. So it would look pretty low.
* go report - I am not sure how useful this is for us. We aren't a library that other people are selecting from among many libraries, so knowing how well we align to this standard won't help people make any decisions.
* Meshery - I don't believe that this is relevant to our project.
* license - This information is already displayed by GitHub directly on our project page 
![Screen Shot 2021-06-17 at 12 33 14 PM](https://user-images.githubusercontent.com/1368985/122446404-3fde1700-cf68-11eb-9956-a43b72090ecd.png)
* help wanted issues - this is neat! I would like to see us use this badge. I wonder if we can configure it to show both help wanted and good first issue label counts?
* website - I think this is a status badge for if the website is up? I don't see this as being too useful to us at the moment.
* twitter/slack - we have a prominent header for contacting the project on our readme that lists out the best ways to talk to us. I think that is more clear than the badges.

**Comment by shikharcodes** [comment]
Hey @DARK-art108, which badges are required to be added to the README file? I would be happy to work on adding them.
