### ISSUE TITLE
Example bundles don't all work with v1 prerelease

### ISSUE THREAD

**Issue by divbhasin** [getporter/porter#1647]
## Describe the bug
The https://porter.sh/quickstart/#understand-a-bundle section has the following command:
```
$ porter explain --reference getporter/wordpress:v0.1.3
```

However, running it produces
```
Error: unable to pull bundle before invoking explain command: unable to pull bundle getporter/wordpress:v0.1.3: unable to load bundle getporter/wordpress:v0.1.3 from cache: error unmarshaling the typed manifest: yaml: unmarshal errors:
  line 10: cannot unmarshal !!seq into manifest.Dependencies
```

## To Reproduce
1. Run `porter explain --reference getporter/wordpress:v0.1.3`
2. See error

## Expected behavior
There should be no yaml errors and it should give the normal explain output

## Version
porter v1.0.0-alpha.0-5-g170abf4e (170abf4e)

**Comment by divbhasin** [comment]
I figured out the issue here but do not know where the wordpress bundle lives to patch it. Essentially, the bundle's `porter.yaml` file should have:
```
dependencies:
     requires:
           - name: mysql
           - ...
```

instead of 

```
dependencies:
     - name: mysql
     - ...
```

**Comment by carolynvs** [comment]
@divbhasin Unfortunately this is due to us making a breaking change in the v1 prerelease of Porter. The examples all work with the current stable release of Porter, (v0.38.3).

I am not sure that there is a good way to avoid this problem and we need a v1 page on the site that explains things like this as there may be more down the road.

If you install the latest stable version of Porter, not the v1 prerelease, then that explain command should work!

**Comment by carolynvs** [comment]
The long term fix for this is coming in https://github.com/getporter/porter/issues/1956.
