### ISSUE TITLE
How to properly bind local folder using docker-compose mixin

### ISSUE THREAD

**Issue by jaudiger** [getporter/porter#1661]
**What is your question?**

I'm trying to bind a local folder using docker-compose.yml, I first tried with a complex docker-compose.yml file, and I was getting weird problems. After few investigations, I found the culprit, and I think I missed something. Right now the volume is not bound correctly when using the porter tool, but if I'm only using the docker-compose tool, it's working as expected.

**What have you tried already?**

```log
➜ tree
.
├── docker-compose.yml
├── porter.yaml
└── test
    └── log.txt

1 directory, 3 files
```

[porter_test.zip](https://github.com/getporter/porter/files/6758651/porter_test.zip)

**Where have you looked already to figure this out?**

I looked at the docker-compose mixin example: https://github.com/getporter/docker-compose-mixin/tree/main/examples/compose and this blog: https://porter.sh/blog/migrate-from-docker-app/

**Comment by vdice** [comment]
Hi @jaudiger, thanks for the issue and for uploading the sample bundle - very helpful.

The issue here is subtle.  Because bundles using docker compose are always setup to use the host docker socket/daemon, the volumes for any compose app containers are thus relative to the host, as opposed to locally inside the installer image.  Specifically, for the example bundle you've provided above, the docker daemon knows about directories on the host but does not see/know about the `test` directory existing inside the running installer container.

It is possible to set things up so that directories/files inside the running installer container can be added to Docker volumes and then used by Docker Compose application containers.  Check out this sample: https://github.com/vdice/porter-bundles/tree/master/wip/dockerapp

The bundle consists of the following components, which should mostly be familiar:

- The [Docker Compose setup](https://github.com/vdice/porter-bundles/blob/master/wip/dockerapp/docker-compose.yml) consists of one single `busybox`-based "app" which uses a Docker volume for its data ("myvol")
- The [helpers.sh script](https://github.com/vdice/porter-bundles/blob/master/wip/dockerapp/helpers.sh) primarily features the setup of the "myvol" Docker volume and copies in both a file baked into the invocation image ("config.toml") and a file generated at runtime from a Porter parameter ("echo.txt"), the latter of which could have different contents depending on the user override.  It uses a helper docker container to perform this data volume setup.
- The [Porter manifest](https://github.com/vdice/porter-bundles/blob/master/wip/dockerapp/porter.yaml) ties this all together, at least in the `install` step:
  1. Create the volume and populate it via a helper container
  2. Bring up the Docker Compose app
  3. Print the app logs

**Comment by vdice** [comment]
I also PRed the addition of a similar example bundle to the docker-compose-mixin repo: https://github.com/getporter/docker-compose-mixin/pull/20

**Comment by jaudiger** [comment]
It makes sense! Thanks for your support and to have taken the time to explain to me how to do it @vdice ! It was really really helpful, I think I have enough information to begin to bundle one of my applications which has tremendous dependencies.

I now understand why the docker daemon wasn't finding the local folder. And I better understand how Porter's packaging is working to create a bundle from an application.

I looked at your PR, and you were definitively right to add a new sample talking about this specific subject, it could help other people :smile:

**Comment by vdice** [comment]
Closing this issue as answered and now that we have a corresponding example bundle in the mixin repo: https://github.com/getporter/docker-compose-mixin/pull/20
