### ISSUE TITLE
Publish checksums

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1797]
We need to publish checksums along with our release binaries.

One thing to look into is if our build would work with goreleaser yet. When I last tried to move over to goreleaser I ran into like 100 things that we do that doesn't work with it. From the go build, to things like our latest and canary tags. It could be worth cataloging everything that we do that isn't standard and figure out how we could use goreleaser, and still make things like installing the latest release, or the canary easier.

**Comment by VinozzZ** [comment]
> Traditional checksum systems don’t give any real evidence that the file downloaded has not been tampered with or damaged. It only signifies that the person who was able to modify two separate files on the same server was able to make them agree. There is no evidence available to the person downloading those two files that the person who last modified them is someone they trust. For example, [Linux Mint was compromised in exactly this way 47](https://micahflee.com/2016/02/backdoored-linux-mint-and-the-perils-of-checksums/).
In order to offer evidence that a file has not been tampered with or damaged, it would require a digital certificate as part of the file itself, signed with a key that can be verified by a trusted mechanism. The GitHub releases system works well with these kinds of protocols. When using one of these protocols, checksums are superfluous.

We can store a private key in Porter's build pipeline and then sign the checksum file using that key. However, we need to have a way for users to pull the public key. It would be great if the way to obtain the public key is scriptable, or it's ok to do it manually?

**Comment by carolynvs** [comment]
We can host a copy of our public key either in the github repository and/or on the website, will that work?

**Comment by carolynvs** [comment]
@VinozzZ Can I close this or are you still working on signing too?

**Comment by VinozzZ** [comment]
Yes, I still need to work on the signing part. Here is a new issue that is for signing: #2041
