### ISSUE TITLE
Publish from archive should use a relocation map

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1819]
I was reviewing [this PR](https://github.com/getporter/porter/pull/1815) and that we don't use a relocation mapping file and preserve the original bundle.

See this very wonderfully long function comment for context:

https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/porter/publish.go#L172-L186

This PR is correcting a bug in Porter where when we copy a bundle from one registry to another, we aren't preserving the relocation map. I was checking all the code that I thought would use that function and wasn't clear on why we are essentially "re-publishing" the bundle from the archive instead of preserving the original.

_Originally posted by @carolynvs in https://github.com/getporter/porter/issues/1815#issuecomment-963296356_

Vaughn confirmed that we should update the implementation of publish from archive to preserve the original bundle and use a relocation mapping file.

**Comment by jasmdk** [comment]
I see a behavior which may be the same root cause. I have bundles which are airgapped (includes images from docker.io) and this bundle is pushed to my own registry.
During my continuous integration, I do "porter archive --reference ...." to archive the bundle into a tgz which I can move to my airgapped environment.
On my build agents where I am not authenticated against docker.io and therefore have a lower pull rate limit combined with the fact that all access to docker.io from our corporate location is represented by the same public ip, then I get pull rate limit errors during the "archive" action where I would suspect all the image information is already included, however something insists invoking the docker.io API.
This is hard to reproduce, but once I reached the limit I can not archive my bundle:

`porter archive busy.tgz --reference host.docker.internal:5443/porter-hello:v0.1.0`

`Error: error preparing artifacts: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

**Comment by carolynvs** [comment]
It very well could be related but I'm not confident. I'll try to reproduce and debug this week, as between this and your previous issue I think I have enough to go on.

**Comment by carolynvs** [comment]
I found the original issue that Vaughn made to track this work: https://github.com/getporter/porter/issues/739
