### ISSUE TITLE
Switch from pkg/errors package to Go's errors package

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2009]
Now that go supports erorrs.Is and other nice functionality that we previously relied on pkg/errors to do for us, let's get off of that and use the built-in errors package.

As I work on new features, I'll update as I go but it would be great if we could do a sweep get everything consistent.

**Comment by joshuabezaleel** [comment]
1. The functionality that I found so far on the codebase using `pkg/errors` that can be substituted with `errors` package are `Is` and `New`. Does this mean that we will be using the built-in errors package for those two and will still be using `pkg/errors` for other that hasn't supported e.g. `Wrap()` and `WithStack()`? 
2. If the answer to no 1 is yes, supposed that we have a file where there are `Is()` function which we will use built-in `errors` and `Wrap()` function which we will use `pkg/errors`. Since those two have the same name, is it safe to alias the `pkg/errors` to other on import e.g.
```
import (
   "errors"
   
   pkgerrors "github.com/pkg/errors"
)

func someFunction() {
   ...
   errors.Is(
   ...
   pkgerrors.Wrap(
}
```

**Comment by carolynvs** [comment]
@joshuabezaleel For now, please hold off on taking on any more issues until your current PRs are merged. I want to give other people a chance to take on these types of issues since they are great for people new to Porter. Plus having PRs open for a long period of time really increases the likelihood that the merge conflicts will get real bad.

**Comment by joshuabezaleel** [comment]
@carolynvs Ah yes, I was getting carried away since the issue was on the top recent and it piqued my interest. I thought at first it will already go for Jeremy to tackle on. I'll get back and try to finish the other of my PRs by this week. So sorry and thank you for the kind reminder, Carolyn!
