### ISSUE TITLE
Built-in secret store for trying out porter

### ISSUE THREAD

**Issue by VinozzZ** [getporter/porter#2012]
#1027  enforces porter to store sensitive data into a secret store instead of porter's database. This would force user to setup a secret store when running Porter. It would require extra manual steps from a new user who just want to give Porter a try.
We should come up with a strategy that still allows people to try out porter but ensure that no user will accidentally use porter without a secret store in production

**Comment by VinozzZ** [comment]
Current idea is, by default, there isn't an secret plugin configured that can be used to store secret data. 
However, users will have the option to use a local file system based secret plugin for testing and development purpose.
The file based secret plugin will have permission set to only allow current user to access the data

**Comment by carolynvs** [comment]
👍  Also when you don't have a secret store configured, you can only run bundles that:

* Do not use sensitive parameters
* Do not generate sensitive outputs

(It's not a problem for credentials since they are never stored.)

When you try to run a bundle that won't work without a secret store, porter will print an error telling you to configure a secret store and link you to the documentation.
