### ISSUE TITLE
Porter for Bundling Ansible Playbook

### ISSUE THREAD

**Issue by ProfessorManhattan** [getporter/porter#2047]
This seems to be somewhat outside of what Porter is currently intended for but the fact that you can distribute the images over registries sparked enough interest for me to consider using this for bundling an Ansible Playbook for an offline install. The playbook installs everything - npm packages, apt-get repos, yum, pip, git repositories, etc. Is there anyway Porter can be used to bundle standard installation sources so that an operating system can be bundled with the installation assets to perform an offline install with an Ansible playbook?

If not, are there any other solutions you might recommend? How might Porter be able to help me achieve this goal?

I'm basically trying to use Porter to bundle together an OS update.

**Comment by carolynvs** [comment]
What type of assets are you looking to distribute? If they can be saved as files into the same directory tree as the bundle (where the porter.yaml lives), then those files will be distributed with the bundle and you can access them when the bundle runs.

I'm a bit fuzzy on what would need to happen to get the files to the target environment but you can use tools like scp and rsync to copy files to the target if needed (since bundles don't have direct access to the host).

Does that help at all?
