### ISSUE TITLE
PEP-003 current status

### ISSUE THREAD

**Issue by nsemikov** [getporter/porter#2315]
**What is your question?**
I want to understand when pep-003 will be implemented and maybe help with this work. What is the current state of pep-003?

**What have you tried already?**
I tried to find state of pep-003 on [roadmap](https://github.com/getporter/porter/projects/4), [project board](https://github.com/orgs/getporter/projects/1) and [pep-003 page](https://github.com/getporter/proposals/blob/main/pep/003-dependency-namespaces-and-labels.md) and couldn't find it.

**Comment by carolynvs** [comment]
PEP 003 is in the proof of concept stage on our roadmap (under Advanced Dependencies). I just realized that it accidentally linked to PEP 004, and I have fixed that card to link to the correct PEP.

We have a design, and I have done some initial work to vet it under the [pep003-advanced-dependencies label](https://github.com/getporter/porter/issues?q=label%3Apep003-advanced-dependencies+). Further work has stopped while I have shifted focus to releasing v1 this month.

I would like to get https://github.com/getporter/porter/pull/2099 updated, split out into smaller PRs and merged before trying to coordinate adding more people to the feature, so that we can better isolate and define tasks that people can help with. Unfortunately the feature isn't in a state yet where I can just point to curated issues that someone could understand and take on without much coordination.

**Comment by nsemikov** [comment]
Thanks for the quick response!

**Comment by carolynvs** [comment]
I anticipate that we will start work on this immediately after v1 is released and get it split up so that people can help implement. 👍 The best way to keep up to date on that would be to join our Slack channel, and we'll probably have some additional coordination in our community meetings.

https://getporter.org/community

 If you can't attend those it's not a big deal, let's just keep in sync over Slack so that you can jump in and help when we start on that feature. I really would appreciate help both with reviewing the design, trying out the feature on realistic bundles, obviously implementing it, and writing documentation. So there's plenty of work for us to all share. 😁
