### ISSUE TITLE
Porter upgrade should not be allowed when a bundle has not been successfully installed

### ISSUE THREAD

**Issue by VinozzZ** [getporter/porter#2355]
## Describe the bug

Currently, Porter allows upgrade action be performed on a failed installation. This may potentially cause unexpected behavior since the state from install action is never achieved. 

## To Reproduce

1.    Run porter create
2.    modify helpers.sh to exit 1 in install function
3.    Run porter build
4.    Run porter install - it will fail
5.    Run porter list - it will show installation as defined
6.    Run porter upgrade - it will pass
7.    Run porter list - it will show installation as defined

## Expected behavior

During an deployment, an installation could fail. A user is expected to retry the install action again until the bundle is successfully installed. Only after then, should an upgrade action on the bundle be permitted. 

## Porter Command and Output
```
$ porter -n test install
executing install action from porter-hello (installation: test/porter-hello)
Install Hello World
Hello World
Error: error running command /cnab/app ./helpers.sh install: exit status 1
exit status 1
1 error occurred:
        * mixin execution failed: exit status 1


1 error occurred:
        * mixin execution failed: exit status 1


1 error occurred:
        * container exit code: 1, message: <nil>


$ porter -n test list
------------------------------------------------------------------------------
  NAMESPACE  NAME             VERSION  STATE        STATUS     MODIFIED
------------------------------------------------------------------------------
  test       porter-hello     0.1.0    defined      failed     9 seconds ago
 
$ porter -n test upgrade
executing upgrade action from porter-hello (installation: test/porter-hello)
World 2.0
World 2.0
execution completed successfully!

$ porter -n test list
------------------------------------------------------------------------------
  NAMESPACE  NAME             VERSION  STATE        STATUS     MODIFIED
------------------------------------------------------------------------------
  test       porter-hello     0.1.0    defined      succeeded  4 seconds ago
```

## Version
Copy the output of `porter version` below

porter v1.0.0-rc.1 (https://github.com/getporter/porter/commit/8e005d5cc224eb5c94f4dd8f5feb1f78c50002f3)

**Comment by jasmdk** [comment]
Maybe this should also have some kind of "force-install" workaround or some way of adjusting the porter perception of the installation like changing "defined" into "installed".
Just because one of the steps during "install" fails, it does not mean that everything is being rolled back and can be repeated. In one scenario we deploy Hashicorp Vault and initializes it and as initilizing means generate an encryption key and encrypt the database, then this can not be repeated. If we get past this step, we will be able to upgrade, but not repeat the install sequence.
That reminds me of another problem - if install fails, the output parameter containing this encryption key is not available, so we can not export it and use it for future steps.

**Comment by carolynvs** [comment]
@jasmdk If you are seeing failed runs of porter not make the outputs that were generated during the run available afterwards, can you open a bug report with details? As long as the step in install which generated the output completes, then porter should make the output available via the `porter installation outputs` commands.
