### ISSUE TITLE
Installation showing up as defined after a run has failed

### ISSUE THREAD

**Issue by VinozzZ** [getporter/porter#2357]
During the investigation of #2353 , we discovered when a bundle installation has failed, its state is showing up as `defined`
This seems to cause confusion for users due to the lack of definition of what `defined` means.

## To Reproduce

1. Run porter create
2. modify helpers.sh to exit 1 in install function
3. Run porter build
4. Run porter install - it will fail
5. Run porter list - it will show installation as defined

## Expected behavior

We would like to improve our doc and the bundle state being displayed from porter

## Version

porter v1.0.0-rc.1 (https://github.com/getporter/porter/commit/8e005d5cc224eb5c94f4dd8f5feb1f78c50002f3)

**Comment by carolynvs** [comment]
Now that I'm looking at this further, I am not 100% sure what we want to change here. 

Right now this is what is happening:

1. The user created an installation and porter tried to install it. (state: defined)
2. The installation failed to complete (status: failed)

The original reason why I called the state defined is that porter knows about it, and will prevent someone else from trying to use the same name. You can see information about it, (view the definition).
It is not installed at this point, the resources represented by the bundle do not exist yet.

```
-------------------------------------------------------------------------
  NAMESPACE   NAME            VERSION  STATE      STATUS     MODIFIED
-------------------------------------------------------------------------
  quickstart  azure-tf        0.1.0    defined  failed  2022-09-08
  quickstart  creds-tutorial  0.3.0    installed  succeeded  2022-08-31
```

I get that the state of defined isn't documented and we should fix that. But the bug report here says that the state should be installed which would not be accurate.

So I'm wondering if the only problem is documentation (or that it should be called state: unknown instead of defined). I don't think that we should actually call it installed until an installation was successful though.

**Comment by VinozzZ** [comment]
> Now that I'm looking at this further, I am not 100% sure what we want to change here.
> 
> Right now this is what is happening:
> 
>     1. The user created an installation and porter tried to install it. (state: defined)
> 
>     2. The installation failed to complete (status: failed)
> 
> 
> The original reason why I called the state defined is that porter knows about it, and will prevent someone else from trying to use the same name. You can see information about it, (view the definition). It is not installed at this point, the resources represented by the bundle do not exist yet.
> 
> ```
> -------------------------------------------------------------------------
>   NAMESPACE   NAME            VERSION  STATE      STATUS     MODIFIED
> -------------------------------------------------------------------------
>   quickstart  azure-tf        0.1.0    defined  failed  2022-09-08
>   quickstart  creds-tutorial  0.3.0    installed  succeeded  2022-08-31
> ```
> 
> I get that the state of defined isn't documented and we should fix that. But the bug report here says that the state should be installed which would not be accurate.
> 
> So I'm wondering if the only problem is documentation (or that it should be called state: unknown instead of defined). I don't think that we should actually call it installed until an installation was successful though.

I see. That makes sense. Then I agree that it's more of a documentation problem. I will move documentation task from #2356 to here

**Comment by schristoff** [comment]
I believe where we would want to add this is somewhere [in this page](https://porter.sh/end-users/installations/)
What we could create is a table of installation state/statuses and what they mean - this could be a good first issue :)
