### ISSUE TITLE
Error: unable to pull bundle before upgrade: unable to pull bundle

### ISSUE THREAD

**Issue by pselmani** [getporter/porter#2585]
Hi,

Can anyone help please. I have ran the 'make bundle-build\publish\register' on a workspace_service bundle. It registered with API (Azure). When I clicked on it to create a new Workspace Service I get the below error

Resource Id
: 583446c7-5081-44ba-8b20-22bd0b32fabd
Resource Path
: /workspaces/a3384f46-c377-44d8-95f8-de5d5d01a7c7/workspace-services/583446c7-5081-44ba-8b20-22bd0b32fabd
Resource Version
: 0
Status
: deployment_failed
Action
: install
Message
: 583446c7-5081-44ba-8b20-22bd0b32fabd: Error context message = Error: unable to pull bundle before installation: unable to pull bundle trect07acr.azurecr.io/tre-workspace-service-psstorage:v0.1.1: error reading porter.yaml for trect07acr.azurecr.io/tre-workspace-service-psstorage:v0.1.1: error unmarshaling custom action schemaVersion: yaml: unmarshal errors: line 1: cannot unmarshal !!str 1.0.0 into manifest.Steps az login --identity -u 7500626c-b78a-49c5-bd19-2e9a47807d08 && az acr login --name trect07acr && porter install "583446c7-5081-44ba-8b20-22bd0b32fabd" --reference trect07acr.azurecr.io/tre-workspace-service-psstorage:v0.1.1 --allow-docker-host-access --force --cred ./vmss_porter/arm_auth_local_debugging.json --cred ./vmss_porter/aad_auth.json

my Porter.yaml looks like this

schemaVersion: 1.0.0
name: tre-workspace-service-psstorage
version: 0.1.1
description: "A storage account workspace service"
dockerfile: Dockerfile.tmpl
registry: azuretre

**Comment by carolynvs** [comment]
@pselmani Can you check which version of the porter cli you are using by running `porter version`?

**Comment by pselmani** [comment]
@carolynvs 

(main) $ porter version
porter v1.0.4 (e3a2a5ef)

**Comment by carolynvs** [comment]
I'm not very familiar with Azure TRE's development environment but based on the porter install command, and that you are seeing porter version return v1 (which does support `schemaVersion`), I believe that you are running into problems because the bundle is built with porter v1, but the porter cli running the install command is porter v0.

Are you perhaps running the porter install command inside a container or with an automated script? Porter v1 doesn't support the `--cred path/to/cred.json` flag anymore for porter install.

I'm guessing that the environment where the porter install command is being run is out-of-date (both with an old version of porter and older scripts that were written to work with porter v0). Can you try updating your environment / container where you run your porter commands?

If that doesn't help, I encourage you to reach out directly to the Azure TRE team and I'm sure they can help you get your environment set up properly.

**Comment by pselmani** [comment]
Thanks @carolynvs, so the issue was a mismatch between TRE solution and Porter Version (in devcontainer)

**Comment by carolynvs** [comment]
I'm glad you got it figured out! 🎉
