### ISSUE TITLE
Fix lint and vet issues found on Go 1.20

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2727]
Porter currently builds on Go 1.19 and staticcheck/vet doesn't find any problems. When you install Go 1.20 and run that command however, a bunch of problems are now found. Before we can update our CI to build with Go 1.20, those issues need to be fixed.

## Steps
1. Install Go 1.20
2. Install the latest version of staticcheck that works with Go 1.20.
3. Run `staticcheck ./...` and `go vet` and correct any problems reported. Don't use the mage targets, and use those binaries specifically so that you are sure that you are using the version of the tools for Go 1.20.
4. Figure out if we need to update the version of staticcheck installed by our magefiles repository in the EnsureStaticCheck function (below)

   https://github.com/getporter/magefiles/blob/4f470a57933c3cac24c57ba40ec91a325f08745e/tools/install.go#L111-L113

**Comment by troy0820** [comment]
This lift is going to change the testing because one of the errors with `go vet ./...` was 
`loop variable supported captured by func literal`. This means that the t.Parrallel() was testing one of the test scenarios from the list of `SupportedExtensions` 
```go
DependenciesV1Extension,
DependenciesV2Extension,
DockerExtension,
FileParameterExtension,
ParameterSourcesExtension,
``` 
In the screenshot below you can see the output of the log statement added for debugging proves the only extension getting tested is `ParameterSouresExtension`.  This is also happening in the cache package as well.  

[Why this happens](https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables)
![image](https://github.com/getporter/porter/assets/5985850/dc0780ce-a7e8-4d69-b318-872c12837cdd)

I am currently working on this.
