### ISSUE TITLE
bug: Mage Install runs into "no such file or directory"

### ISSUE THREAD

**Issue by schristoff** [getporter/porter#2989]
[It's somewhere around here](https://github.com/getporter/porter/blob/main/magefile.go#L656)

```
mage Install
installing Porter from bin to /Users/schristoff/.porter
Error: remove /Users/schristoff/.porter/mixins/arm/arm: no such file or directory
```

**Comment by Bharadwajshivam28** [comment]
@schristoff  can you please assign me this ?

**Comment by schristoff** [comment]
Here's some light debug steps I would use to start figuring out what is happening:

Goal: Figure out exactly where the error is occurring.
Assumption: Since the error is about removal of a mixins directory, I can safely assume [it is in here](https://github.com/getporter/porter/blob/main/magefile.go#L682) - if we comment out these lines (682-683), what happens?

Goal: Figure out **how to stop the error**
Assumption: We have this [for loop](https://github.com/getporter/porter/blob/main/magefile.go#L662) iterating over all directories it finds on [L657 ](https://github.com/getporter/porter/blob/main/magefile.go#L657) - what directories is it finding? 

End Goal: We still want to copy any existing `/bin/mixins` over, because if I have an arm or terraform mixin installed, I want to use it with my newly locally built Porter bundle. The goal is to copy over all existing and relevant porter bin * directories, while leveraging the newly built executable. 

@sgettys  is welcome to share his debugs steps he'd go through as well.

**Comment by Bharadwajshivam28** [comment]
> Here's some light debug steps I would use to start figuring out what is happening:
> 
> Goal: Figure out exactly where the error is occurring. Assumption: Since the error is about removal of a mixins directory, I can safely assume [it is in here](https://github.com/getporter/porter/blob/main/magefile.go#L682) - if we comment out these lines (682-683), what happens?
> 
> Goal: Figure out **how to stop the error** Assumption: We have this [for loop](https://github.com/getporter/porter/blob/main/magefile.go#L662) iterating over all directories it finds on [L657 ](https://github.com/getporter/porter/blob/main/magefile.go#L657) - what directories is it finding?
> 
> End Goal: We still want to copy any existing `/bin/mixins` over, because if I have an arm or terraform mixin installed, I want to use it with my newly locally built Porter bundle. The goal is to copy over all existing and relevant porter bin * directories, while leveraging the newly built executable.
> 
> @sgettys is welcome to share his debugs steps he'd go through as well.

Thanks looking in it

**Comment by Bharadwajshivam28** [comment]
@schristoff  

Here are few things to discuss and i noticed-

1) Commenting out line no 682 and 683 fixes the issue

![Screenshot from 2024-02-08 23-30-42](https://github.com/getporter/porter/assets/108119109/b9ff8a2a-a3a6-4572-953d-f9d0a6a07b2e)

2) But i added some line to Print loop info. Inside the loop then i got some lines with the output-

![Screenshot from 2024-02-08 23-34-53](https://github.com/getporter/porter/assets/108119109/86db7393-973b-4117-ac00-eddb082e4942)

3) Printed contents of the  destination directory
![Screenshot from 2024-02-08 23-38-03](https://github.com/getporter/porter/assets/108119109/cc67512a-c785-4a39-9387-6c236eae2a0e)

The issue is fixed from the point 1 but we can add these debug info if we need more clarity...
