### ISSUE TITLE
Report the use of components with vulnerabilities in porter

### ISSUE THREAD

**Issue by HouqiyuA** [getporter/porter#3102]
Dear Team Members:
Greetings! Our team is very interested in your project. we performed source code perspective security analysis (SCA) and vulnerability library association analysis on this project and found that components with vulnerabilities are still being used into this project.We would like to report this issue to you,so that you can fix and improve it accordingly. I add the details in json file below. Please confirm whether this problem really exists and confirm with us. Looking forward to hearing from you and discussing more details with us, thank you very much for your time and attention.

Note: Each "affect_components" field in the report represents the vulnerable component introduced by this project. The other is the vulnerability information associated with it.

Qiyu Hou

[porter-main_report.json](https://github.com/getporter/porter/files/15243538/porter-main_report.json)

**Comment by schristoff** [comment]
Hey @HouqiyuA  - thank you for bringing this up. We are resolving these, and it should be fixed in the 1.1.0 release in June. For future requests, could you please take a look at our [security policy and reporting here](https://github.com/getporter/porter/blob/main/SECURITY.md)?

I'll be closing this now, but this is getting worked on :)
