### ISSUE TITLE
Porter mixin interoperability version

### ISSUE THREAD

**Issue by vdice** [getporter/porter#453]
Porter may have a need/use for a version designating interoperability between it and a mixin.  

This could be the porter version (tag value) or a different field added to the mixin schema.

Porter could then ensure that the version declared in the mixin schema is above a certain threshold before running.  Alternatively, if the mixin declares a version that Porter doesn't understand/support, it could error out and/or inform the user.

Or, can/should we just use the mixin binary version itself for comparison/interoperability?

**Comment by carolynvs** [comment]
Closing, this will be addressed as part of [PEP 005](https://github.com/getporter/proposals/blob/main/pep/005-mixins-are-bundles.md). We are going to need to add additional metadata to the bundle.json for mixin bundles, since they are not normal porter bundles are much closer to a vanilla CNAB bundle and we can use that to tell if it's compatible or not.
