### ISSUE TITLE
Support mounting volumes for install/uninstall commands

### ISSUE THREAD

**Issue by danielegallingani** [getporter/porter#475]
I have a use case in which I would like to bind-mount a file in the install process.
After exploring the codebase, it is not clear whether it is possible or not to define volumes/mount points in the porter.yml or in any other place.

Is this something left to mixins specification?

**Comment by gabro** [comment]
Specifically regarding `unix:///var/run/docker.sock`, it seems it was removed from duffle in https://github.com/deislabs/duffle/pull/661, but I don't understand how to add it back from porter.

More context: I work with @danielegallingani and we're trying to integrate (via a mixin) a Terraform module that uses the Docker provider, so it needs `docker.sock` while installing.

**Comment by carolynvs** [comment]
Closing for now since it's not on the roadmap at this time.

If we still want to add support for local volume mounts (which won't work with the Porter Operator), it would need to be in conjunction with the docker setting and the --allow-docker-host-access flag and we would need a [proposal](https://github.com/getporter/proposals) for how to make that work well with the rest of Porter, i.e. would the bundle need to specify if it wants a volume mounted?

As part of [PEP 005](https://github.com/getporter/proposals/blob/main/pep/005-mixins-are-bundles.md) we are adding support for mounting temporary volumes into a bundle, but the volume wouldn't be a host volume. Maybe once that's complete we will have more ideas of how we could achieve this. Alternatively, we could consider other ways to target the current host using credentials, which would bypass the need for special changes to porter. For example passing a ssh key for the host into the bundle and using that to drop files or run commands on the host.

**Comment by maniSbindra** [comment]
Hi can you please assign this issue to me. Thanks, Mani
