### ISSUE TITLE
Porter should print a clear message that the bundle has changed and is being rebuilt first

### ISSUE THREAD

**Issue by nunix** [getporter/porter#500]
Hi team,

while testing an image with "Docker in Docker", I faced a very strange bug with the latest release:
when running `porter credentials generate`, Porter actually tries to install the bundle:
![image](https://user-images.githubusercontent.com/905874/62513878-bc0c5d00-b81d-11e9-880d-89944152071f.png)

In the screenshot, you can see both attempts from Windows Powershell and WSL (ubuntu).

My "credentials" section looks like this:

```yaml
credentials:
  - name: k3dip
    env: HOST_IP
```
Thanks a lot for your feedback :)

**Comment by vdice** [comment]
Hi @nunix !  I can see this behavior has been surprising.  However, I believe it is a 'feature' that porter rebuilds the bundle (in some cases) prior generating credentials.

It will do so if the hash of the porter manifest (`porter.yaml`) doesn't match the hash included in a pre-existing `bundle.json` file.  The thinking is that porter should perform this rebuild of the `bundle.json` file in these cases before generating credentials, otherwise the creds it sees to generate may be outdated (per the outdated `bundle.json`).  cc @carolynvs for confirmation.

Perhaps we could/should think about how to reduce the UX surprise here; and/or inform the user better on what is occurring.

**Comment by nunix** [comment]
Hi @vdice :)
thanks a lot for your feedback and I totally understand the "rebuild" part.
My "surprise" though, it's that it started **before** I could enter the credentials with `porter credentials generate`.

If it's working as intended, and the credentials generation would come after the rebuild, I will then fix my bundle (docker part) and see if I'm asked to enter my values again (that's what I was expecting to see with `porter credentials generate`)

thanks again for your time and feedback

**Comment by carolynvs** [comment]
Yes, that is what porter is doing. A few commands rely upon a generated file `.cnab/bundle.json`, those commands are: `install`, `upgrade`, `uninstall`, `invoke` and `credentials generate`. They rely upon the generated bundle.json because they can work with bundles made by porter **or** bundles created by other CNAB tools such as duffle or docker app. So porter detects when the porter.yaml has modifications and will do a rebuild before before those commands to ensure that you are not working against a stale bundle.json.

Seems like we have two good follow-ups:

1. Add this answer here to the FAQ
2. Add output that says that we have detected changes to the porter.yaml and are rebuilding the bundle before proceeding.

**Comment by squillace** [comment]
Both 1 and 2, but 2 is the critical step. No one will be suprised if porter says, hey, I have to rebuild the bundle because there have been changes.

**Comment by carolynvs** [comment]
Let's print a message when we detect that the bundle is out of date and we start a rebuild. Something like "Changes have been detected to porter.yaml, rebuilding the bundle before proceeding...".

Here is the area where we determine if we need to rebuild a bundle:

https://github.com/getporter/porter/blob/8b61fc1ffb655aa18863877be3662c789138fe9d/pkg/porter/stamp.go#L31-L42
