### ISSUE TITLE
UX: Streamline custom action invocation

### ISSUE THREAD

**Issue by squillace** [getporter/porter#542]
Hi all, 

When working with custom actions, I find it odd to have to write `porter invoke --action <name>` when I use specified actions like `install` and pass a name without `porter install --name <bundle name>`

Can we dispense with action, given that `invoke` is the execution verb and OBVIOUSLY the next name will be the verb to invoke? Surely I'm overlooking something.

**Comment by carolynvs** [comment]
I'm not sure I am following?

Here's how the commands work just to get on the same page:

* `porter install [INSTANCE_NAME]`
* `porter invoke --action ACTION_NAME [INSTANCE_NAME]` where ACTION_NAME is the name of the action inside of the bundle you want to run, e.g. `dry-run` or `status`, etc.

In both commands INSTANCE_NAME is optional and defaulted to the name of the bundle found in the current directory or that was specified from `--tag`. I'm using instance name because that's what we have decided on, that's not what the help text says today, this is the claim name under the hood.

Based on those commands above, can you help point out which flag or argument is redundant or could be guessed by porter? Or is it another one that I didn't list?

**Comment by squillace** [comment]
I missed this response, my bad. I meant I expected to use `porter invoke com.azure.enable-instance -c foo --tag squillace/azuredataservices:v0.1.1` instead of passing `invoke --action com.azure.enable-instance`. A very small issue, but if you're going to use the `invoke` verb, the next argument _must_ be the action name, right?

**Comment by carolynvs** [comment]
Ah thanks I understand the question now, thanks for clarifying. One core design decision for Porter's CLI is to not have multiple positional arguments where the order of the arguments is significant. This is a best practice that I have developed after working on CLIs over the years.

Here's the current syntax for `invoke`:

`porter invoke [INSTANCE] --action ACTION [flags]`

It has a single positional argument, the name of bundle instance (claim) that you want to work against. When you are using porter "in dev mode", and are in the directory of the bundle's source files you have the luxury of omitting the instance, but for anyone who installed from a tag they have to specify the instance name.

Let's consider what that command looks like if the action name is also a positional argument.

`porter invoke [INSTANCE] [ACTION] [flags]`

Now people being people they are going to forget the order (just like we do every time we create a symlink with `ln -s` and sometimes type `porter invoke customaction HELLOWORLD` and other times they will type `porter invoke HELLOWORLD customaction`. 

It leads to the user always feeling a bit of "_which wire should I cut the blue one or the green one_" every time they type the command, and needing to check the help text each time before they run it, or they YOLO it and hope that Porter has extra smarts built in or good error messages to tell them to fix what they typed.

I hope that explains the why behind the best practice that we are following, which is to only use a single positional argument, the name of the resource to act upon, and explains why action is a flag.

**Comment by carolynvs** [comment]
I think I've answered the question so I'm closing this. If there's still more to hash out, let me know!
