### ISSUE TITLE
porter-kustomize mixin alpha-0.1

### ISSUE THREAD

**Issue by donmstewart** [getporter/porter#576]
Initial attempt at a porter mixin to support `kustomize` (the standalone binary) for feedback.

GHRepo: https://github.com/donmstewart/porter-kustomize
Docs: https://donmstewart.github.io/porter-kustomize/

Feedback greatly appreciated. Still working on the test cases so I know they need fixing but the plugin should work for `install` and `uninstall` steps.

Example `porter.yaml` can be found in the documentation at https://donmstewart.github.io/porter-kustomize/examples/

**Comment by carolynvs** [comment]
The kustomize mixin looks really good and our documentation especially is 🤩!

If you would like an example of how to support [custom actions](https://porter.sh/authoring-bundles/#custom-actions), I suggest taking a look at the recently updated [exec mixin](https://github.com/deislabs/porter/tree/master/pkg/exec), especially its schema (patternProperties).  It would be a near copy of what you have already for upgrade, unless you wanted to let the user run any arbitrary kustomize command in a custom action.

I wanted you to be aware of two changes to mixins that are coming very soon that may impact your mixin:

* https://github.com/deislabs/porter/issues/263. I plan on making this change in all our mixins this week. Porter will try to call version with the flag on mixins. If you can't make the change soon, no worries, porter will fall back to just displaying the mixin name, without the additional metadata from the `--output flag` if it's not supported.
* https://github.com/deislabs/porter/issues/262.

I read your code and my only suggestion would be around making the mixin as robust as possible to unanticipated state, and being able to handle it gracefully. I'm not familiar with kustomize so if that's not an issue (maybe kustomize handles this all itself), then feel free to say "this doesn't apply!". 😀  

For example, being asked to delete a resource that is already deleted. Or create one that already exists with the same identifier and ensure that all the values match what was requested.

Often a bundle can get into a state where 25% of install completed but then something failed and the user needs to re-run install again. That first 25% needs to be okay with being re-run again, so that the remaining 75% gets a chance to be installed. Same concept applies for upgrade and delete. 

Just something to think about and see if it applies or not to Kustomize. I have been finding it that does to some of our other mixins! 😊

**Comment by donmstewart** [comment]
Firstly, thanks for the detailed feedback thats great and I appreciate the time it took.

I'll take a look at the custom actions etc. and read through the two changes to try to get it aligned asap.

For the robustness, yes indeed there a number of things that need to be a lot better right now. Re-running etc. as you mentioned needs some consideration I have not done yet for sure. I'll be sure to address more things this week based on your feedback.

Thanks again!

**Comment by carolynvs** [comment]
In case you are interested (or feel like doing a code review! 😀 ), here is the PR to support listing the mixin versions in `porter mixins list` https://github.com/deislabs/porter/pull/588

**Comment by carolynvs** [comment]
Oh! One more thing I forgot to mention. Once the kustomize mixin is stable and published automatically on new releases let us know where you are publishing them (GitHub releases work just fine) and we will update the porter installer to install the Kustomize mixin by default and it to the [mixins](https://porter.sh/mixins) list.

**Comment by carolynvs** [comment]
Closing since the mixin is now listed in our search index
