### ISSUE TITLE
Bundles w/ Dependencies: Missing cred/param error delayed

### ISSUE THREAD

**Issue by vdice** [getporter/porter#647]
This issue crops up when executing actions from a bundle that includes dependencies.  Take our favorite example, the [wordpress bundle](https://github.com/deislabs/porter/tree/master/build/testdata/bundles/wordpress).  When one installs the bundle, say, without the required parameter `wordpress-password` provided, one doesn't encounter the corresponding error until after the dependency/ies execute (in this bundle, just the mysql dep):

```
 $ porter install -c PORTER_KUBE
Executing dependency mysql...
executing install action from mysql (bundle instance: wordpress-mysql) defined in /cnab/app/porter.yaml
Install MySQL
...
execution completed successfully!
installing wordpress...
Error: invalid parameters: parameter "wordpress-password" is required
```

Therefore, I'm wondering if Porter can surface such errors earlier/prior to running any of the dependencies?

**Comment by carolynvs** [comment]
Oh yeah thanks that is not good at all. Yes we can check for that up-front and we should.

I think this will require a wee bit of surgery on how we currently have the CNABProvider interface so I'm not going to mark this with help wanted. A maintainer should probably tackle it. 

I'm guessing we will want to extract how we load credentials and parameters into a separate function so that we can call that separately from executing the action on a bundle. That way we can validate everything (both the dependencies, and the requested bundle) _then_ execute the dependencies, then execute the bundle. 

We'll have to figure that out when whoever picks this up dives in though.

**Comment by carolynvs** [comment]
Closing since this will be addressed in [PEP 003](https://github.com/getporter/proposals/blob/main/pep/003-dependency-namespaces-and-labels.md)
